"""add_product_prices_table

Revision ID: 42de18617828
Revises: db2da834092b
Create Date: 2026-07-13 17:04:31.223085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42de18617828'
down_revision: Union[str, None] = 'db2da834092b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='检测类别 ID，对应 instances_train2019.json'),
    sa.Column('sku_name', sa.String(length=100), nullable=True, comment='SKU 英文名'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='商品中文名'),
    sa.Column('barcode', sa.String(length=50), nullable=True, comment='商品条码'),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='单价（元）'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='货币'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_prices_category_id'), 'product_prices', ['category_id'], unique=True)
    op.alter_column('training_tasks', 'device',
               existing_type=sa.VARCHAR(length=20),
               comment='Training device: cpu/0/0,1/0-7',
               existing_comment='训练设备：0/1/cpu',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_tasks', 'device',
               existing_type=sa.VARCHAR(length=20),
               comment='训练设备：0/1/cpu',
               existing_comment='Training device: cpu/0/0,1/0-7',
               existing_nullable=True)
    op.drop_index(op.f('ix_product_prices_category_id'), table_name='product_prices')
    op.drop_table('product_prices')
    # ### end Alembic commands ###
